# Generated by Django 5.2.1 on 2025-05-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_title', models.CharField(max_length=200)),
                ('News_summary', models.TextField(blank=True)),
                ('News_content', models.TextField()),
                ('News_day', models.DateTimeField()),
                ('News_url', models.URLField(unique=True)),
            ],
        ),
    ]
