# Generated by Django 5.2.1 on 2025-06-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_title', models.CharField(max_length=200)),
                ('News_summary', models.TextField(blank=True)),
                ('News_content', models.TextField()),
                ('News_day', models.TextField()),
                ('News_url', models.TextField()),
                ('News_keyword', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField()),
                ('User_Password', models.TextField()),
            ],
        ),
    ]
