# Generated by Django 5.2.1 on 2025-06-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField()),
                ('User_Password', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='News_keyword',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='News_day',
            field=models.TextField(),
        ),
    ]
